name: URL Validation
on: [push, pull_request]
jobs:
  URL_Validator:
    name: Run brok Against URLs

    runs-on: ubuntu-latest

    container:
      image: debian:buster-slim

    steps:

    - name: Install System Deps
      run: |
        apt-get update
        apt-get install -y wget libtinfo5

    - uses: actions/checkout@v2

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: .brokdb
        key: ${{ hashFiles('.github/workflows/main.yml') }}-${{ hashFiles('.brokignore') }}-${{ steps.get-date.outputs.date }}

    - name: Install brok
      run: |
        wget https://github.com/smallhadroncollider/brok/releases/download/1.1.0/brok-1.1.0_x86-64-linux.deb
        dpkg -i brok-1.1.0_x86-64-linux.deb
    - name: Run brok
      run: |
        brok --ignore $(cat .brokignore) README.md > /dev/null
